# -*- coding: utf-8 -*-
"""240329_문헌정보학과 202206213 이지원.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGjJr6GBympNlHaJv4UwGtXJv43xmMU5
"""

#분을 입력받아서 시간과 분을 출력하시오.
t=int(input("분을 입력하세요.--> "))
h=t//60
m=t%60
print("{}분은 {}시간 {}분입니다.".format(t,h,m))

#섭씨 온도를 입력받아서 화씨온도를 출력하시오.
C=float(input("섭씨 온도를 입력하세요.--> "))
F=C*1.8+32
print("섭씨 %d도는 화씨 %.1f도입니다."%(C, F))

#원의 반지름을 입력받아서 원의 둘레와 면적을 출력하시오.(PI=3.14)
PI=3.14                     #상수값의 변수명은 주로 대문자로 쓴다.
r=int(input("반지름을 입력하세요.--> "))
c=r*2*PI
a=(r**2)*PI
print("반지름이 {}인 원의 둘레는 {}이고, 면적은 {}입니다.".format(r,c,a))